[book]
authors = ["The ESP-RS Team"]
language = "en"
multilingual = false
src = "src"
title = "Getting started with esp-hal"

[output.html]
git-repository-url = "https://github.com/bjoernQ/esp-hal-getting-started"
